### ISSUE TITLE
Page Load Started

### ISSUE THREAD

**Issue by acuson** [searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global#3]
[Page Load Started DataLayer spec](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/blob/main/Data%20Layer%20Events/Page%20Load%20Started.md)

This event should fire right as the page load begins.

**Comment by nedierecel** [comment]
- [ ] Page Load event fires on page load
- [ ] Content traits from existing dataLayer (initialized on page load) move to this new event.

**Comment by nedierecel** [comment]
- On some pages, the `page_data` loads outside of the event; the event still triggers (See screenshot)


![Image](https://user-images.githubusercontent.com/24525739/236324195-f586ed75-29a4-40fd-8647-67cedb94890b.png)

**Comment by nedierecel** [comment]
@acuson 
- The CJV is sending to the prod GA4 property instead of non-prod GA4 stream. 
- page_load_started fired on this page with History Change: https://model-sitefinity.assurant.com/partner-with-us/vehicle-protection-services - we aren't sending page_view with config tag, so we will explore

**Comment by nedierecel** [comment]
@cdefranco-aiz @Drew-Henderson SD is moving this to the Completed column as it has passed QA.
