### ISSUE TITLE
User Visit Started

### ISSUE THREAD

**Issue by acuson** [searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global#5]
[User Visit Started DataLayer Spec](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/blob/main/Data%20Layer%20Events/User%20Visit%20Started.md)

This event should fire _after_ Page Load Started and _before_ Page Load Completed

- [ ] Event fires once per session

**Comment by nedierecel** [comment]
- Started a new session but did not see the event fire upon my session start. Screenshot included below


![Image](https://user-images.githubusercontent.com/24525739/236833667-e5cb849d-db62-4d90-96e9-612578652c33.png)

**Comment by nedierecel** [comment]
- Search Discovery would prefer that the event load after a tab close not just a window close. Here is the behavior: 

a) I closed the tab, but not the window.
b) Next day I start a new tab and session.
c) User Visit Started does not fire. 
d) GA4 sends their "session_start" event, so this does not match the custom event you are sending. There will be a discrepancy, and we can't leverage the environment variable that is being sent with the custom_session_start event.

**Comment by Drew-Henderson** [comment]
@nedierecel i have a follow up item for Clifton to modify the event as indicated above.  will keep you updated.

**Comment by cdefranco-aiz** [comment]
Hi @nedierecel, the User Visit Started data layer event has been completely removed from our end in Model/QA.

cc: @Drew-Henderson

**Comment by nedierecel** [comment]
@Drew-Henderson @cdefranco-aiz We are confirming the acceptance criteria that this has been removed from Model/QA on .com and .co.uk
