### ISSUE TITLE
Page Load Completed

### ISSUE THREAD

**Issue by acuson** [searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global#6]
[Page Load Completed DataLayer Spec](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/blob/main/Data%20Layer%20Events/Page%20Load%20Completed.md)

Page Load Completed is part of the page load sequence, including virtual page loads in the case of single page apps, and must be the last event pushed in the page load event sequence.

**Acceptance Criteria**
- [ ] Content traits are sent and captured with the Page Load Completed.
- [ ] For the time being, we do not expect values to populate for the Page Load Completed params

**Comment by nedierecel** [comment]
@Drew-Henderson or @cdefranco-aiz - Is there any chance that the new dataLayer values like line_of_business, audience_segment, or variant might be available on page_load_started?

In my earlier notes, you mentioned this is not typically ready until the page fully loads. Let me know if this has changed. Thanks!

**Comment by cdefranco-aiz** [comment]
Hi @nedierecel, the Page Load Completed data layer event has been updated with the latest variables in Model/QA.  Currently, all will return an empty string for the value with the exception of `site_section`.

cc: @Drew-Henderson

**Comment by nedierecel** [comment]
Thanks @cdefranco-aiz I'm confirming all of these are in QA with @KarimiBrown and myself. Our target is to complete QA by COB tomorrow.

**Comment by KarimiBrown** [comment]
Confirming this is still in the data layer 

![Image](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/assets/123565738/19758f71-eba2-4f79-9167-4e1c26310670)

**Comment by nedierecel** [comment]
@cdefranco-aiz @Drew-Henderson We have moved to Done since it is expected that the parameters will be null, with the exception of Site Section. 

Please let us know if you think we might expect this before the mid-July prod release.
