### ISSUE TITLE
Download Link Clicked

### ISSUE THREAD

**Issue by acuson** [searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global#7]
[Download Link Clicked DataLayer Spec](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/blob/main/Data%20Layer%20Events/Download%20Link%20Clicked.md)

This event should be pushed when a download is completed. 

**Acceptance Criteria**
- [ ] Fires only once per download
- [ ] Includes content traits

**Comment by cdefranco-aiz** [comment]
@nedierecel, the Download Link Clicked data layer event is now available in Model/QA.

cc: @Drew-Henderson

**Comment by KarimiBrown** [comment]
Download Link Clicked fires here : 



![Image](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/assets/123565738/3163abb7-0661-4c8e-a3e2-11fb9c223e9e)
