### ISSUE TITLE
Form Started

### ISSUE THREAD

**Issue by acuson** [searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global#8]
[Form Started DataLayer Spec](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/blob/main/Data%20Layer%20Events/Form%20Started.md)

This event should be pushed as a user begins filling out a form.

**Comment by Drew-Henderson** [comment]
@acuson & @nedierecel 
Clifton had a question about the dataLayer value for event_data.type.  Right now i don't know if we have this information on our forms so i think at first the value will be blank/null.

I think the idea for that value is to capture contact us forms vs. gated forms vs. other types of forms we may have on the site.  Is that correct?

**Comment by cdefranco-aiz** [comment]
Hi @nedierecel and @acuson, the Form Started data layer event is now implemented in our Model/QA environment and is ready for validation.

**Comment by nedierecel** [comment]
@cdefranco-aiz Thanks for sending this. We will review. 

From my earlier email, will any of the line-of-business be available on the form event? This was not originally in our scope but thought I would request.

**Comment by nedierecel** [comment]
@cdefranco-aiz On https://model-sitefinity.assurant.com/partner-with-us/multifamily-housing/rent-recovery-solutions, I see the `form_start` event firing 2x in message 182 and 188.

![Image](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/assets/24525739/c517c975-ce79-4676-be45-6b2d101308d9)

**Comment by nedierecel** [comment]
@cdefranco-aiz and @Drew-Henderson Here is a [follow-up video showing](https://www.loom.com/share/aa9b4eccc780420493f401d992f31daa) a form event on the [Commercial form](https://model-sitefinity.assurant.com/partner-with-us/commercial-equipment). 

It seems to be an intermittent issue. @KarimiBrown did not encounter it.

Also, `type` is optional if you have a field you can map to in the CMS, but I also see it captured in the form name (e.g. Commercial Equipment - Contact Form).

**Comment by cdefranco-aiz** [comment]
Hi @nedierecel, thanks for the video.  We'll take a second look and try to reproduce the issue.

For `type`, the value will come in empty for now.

cc: @Drew-Henderson

**Comment by KarimiBrown** [comment]
On that page I am seeing it fire twice as well @Drew-Henderson and @cdefranco-aiz . 

![Image](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/assets/123565738/055e9b1d-c8f0-4f52-9b6f-d5ee57e64de2)

@nedierecel I have only seen it on this form specifically so far.

**Comment by cdefranco-aiz** [comment]
Hi @nedierecel and @KarimiBrown,

I looked into the multiple form_start issue.  It doesn't seem that the additional form_starts are being pushed by our logic (it is not executing when the additional form_starts are pushed).  I'm wondering if it has something to do with the _Form interactions_ automatic event detection setting being enabled on GA4?



![Image](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/assets/131710775/5101ebf4-2907-4917-bf4f-1b1dedf1dce0)

cc: @Drew-Henderson

**Comment by KarimiBrown** [comment]
Form Started firing once here

![Image](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/assets/123565738/f91ee0d4-0dbd-4a39-b230-e2c472c6791c)

**Comment by nedierecel** [comment]
@cdefranco-aiz @Drew-Henderson This has passed QA. One recommendation for event_data.name is to ensure spacing is consistent. For example, if the form name ever changes to "Flood Contact Us", GA4 will treat those as two separate values in the reports.
