### ISSUE TITLE
Form Submission Succeeded

### ISSUE THREAD

**Issue by acuson** [searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global#9]
[Form Submission Succeeded DataLayer Spec](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/blob/main/Data%20Layer%20Events/Form%20Submission%20Succeeded.md)

Form submission succeeded can replace the e_formSubmit event.

**Comment by nedierecel** [comment]
Ready in mid-June

**Comment by KarimiBrown** [comment]
Form Submission Succeeded is firing here : 



![Image](https://github.com/searchdiscovery/Apollo-Documentation-Assurant-Corporate---US-and-Global/assets/123565738/8114316b-b48a-48da-92c9-5db5b886b5bb)

**Comment by nedierecel** [comment]
@Drew-Henderson @cdefranco-aiz Confirming this has also passed QA. Like the `Form Started` event, please ensure spacing stays consistent in the form name.

I'll move to passing QA.
